name: Commit spam bot

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  spam_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit 5 times
        run: |
          for i in {1..5}; do
            echo "a" >> spam.txt
            git add spam.txt
            git commit -m "Add 'a' to spam.txt at $(date) - commit #$i" || echo "No changes to commit"
            git pull --rebase origin main || echo "No remote changes to rebase"
          done

      - name: Push all commits
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
